gazebo_ros_control:
  pid_gains:
    front_left_wheel:
      p: 1.0
      i: 0.1
      d: 0.01
    front_right_wheel:
      p: 1.0
      i: 0.1
      d: 0.01
    rear_left_wheel:
      p: 1.0
      i: 0.1
      d: 0.01
    rear_right_wheel:
      p: 1.0
      i: 0.1
      d: 0.01
